### ISSUE TITLE
tiup playground restart error

### ISSUE THREAD

**Issue by fzhedu** [pingcap/tiup#992] opened 2020-12-15 08:20 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

tiup --tag v408 playground
ctrl +c
tiup --tag v408 playground

2. What did you expect to see?
normal

3. What did you see instead?

Start tiflash instance
TiFlash failed to start: error requesting http://127.0.0.1:2379/pd/api/v1/config/replicate, response: "cannot disable placement rules with TiFlash nodes"
, code 500

mac:tiflash-0 fzh$ tiup --tag v408 playground display
Starting component `playground`: /Users/fzh/.tiup/components/playground/v1.2.5/tiup-playground display
Error: Post http://127.0.0.1:9527/command: EOF
Error: run `/Users/fzh/.tiup/components/playground/v1.2.5/tiup-playground` (wd:/Users/fzh/.tiup/data/v408) failed: exit status 1
4. What version of TiUP are you using (`tiup --version`)?
1.2.5

**Comment by lucklove** [comment] 2020-12-15 08:25
Root cause:  https://github.com/pingcap/tiup/blob/master/components/playground/instance/tiflash.go#L126

The playground will try to set EnablePlacementRules as force to update MaxReplicas if there is tiflash node. However, it seems PD will refuse to this action if there is tiflash node. So the result is that we can start the playground the first time (because pd don't know there is a tiflash yet), but not the second time.

**Comment by JaySon-Huang** [comment] 2020-12-15 08:54
Or we can use this API to update the replica number when the placement-rules is enabled.

https://asktug.com/t/topic/36677/8

**Comment by AstroProfundis** [comment] 2021-08-17 07:09
This is already fixed in #1280

**Closed by AstroProfundis** 2021-08-17 07:09 UTC
Labels: type/bug
