### ISSUE TITLE
tiup playground v6.2.0 -- panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by atidat** [pingcap/tiup#2023] opened 2022-08-17 06:29 UTC
tiup is checking updates for component playground ...
Starting component `playground`: /root/.tiup/components/playground/v1.10.3/tiup-playground v6.2.0
Playground Bootstrapping...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xe65004]

goroutine 1 [running]:
main.(*Playground).terminate(0xc0002ae6e0, 0x9)
	github.com/pingcap/tiup/components/playground/playground.go:990 +0x364
main.execute.func3(0xc00077a280?, {0xc0008a3340, 0x1, 0x1?})
	github.com/pingcap/tiup/components/playground/main.go:291 +0x912
github.com/spf13/cobra.(*Command).execute(0xc00077a280, {0xc000140030, 0x1, 0x1})
	github.com/spf13/cobra@v1.4.0/command.go:856 +0x67c
github.com/spf13/cobra.(*Command).ExecuteC(0xc00077a280)
	github.com/spf13/cobra@v1.4.0/command.go:974 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.4.0/command.go:902
main.execute()
	github.com/pingcap/tiup/components/playground/main.go:352 +0x1032
main.main()

**Comment by qqqdan** [comment] 2022-08-22 02:46
For most cases, this error is caused by the install file is not available in the mirror. It mostly happens during the new package upload and it will be OK after all the new package are uploaded.

**Comment by qqqdan** [comment] 2022-08-24 03:57
v6.2.0 version is released yesterday，and this issue opened 7 days ago.

**Comment by PaulGrandperrin** [comment] 2022-08-27 15:17
Is there a way to work around this issue?
I can't use my dev env anymore at the moment.

**Comment by nexustar** [comment] 2022-09-20 09:57
closed by #1933

**Closed by nexustar** 2022-09-20 09:57 UTC
Labels: type/bug
