### ISSUE TITLE
tiup playground --monitor false is not success

### ISSUE THREAD

**Issue by glkappe** [pingcap/tiup#1521] opened 2021-08-17 09:07 UTC
tiup playground --monitor false is not success,must be --monitor=flase

**[tidb@node4210 conf]$ tiup playground v5.0.3 --tiflash 0 --monitor false --pd 1 --db 1 --kv 1**
Starting component `playground`: /home/tidb/.tiup/components/playground/v1.5.4/tiup-playground v5.0.3 --tiflash 0 --monitor false --pd 1 --db 1 --kv 1
Using the version v5.0.3 for version constraint "v5.0.3".

If you'd like to use a TiDB version other than v5.0.3, cancel and retry with the following arguments:
    Specify version manually:   tiup playground <version>
    Specify version range:      tiup playground ^5
    The nightly version:        tiup playground nightly

Playground Bootstrapping...
The component `prometheus` version v5.0.3 is not installed; downloading from repository.
download https://tiup-mirrors.pingcap.com/prometheus-v5.0.3-linux-amd64.tar.gz 2.37 MiB / 39.84 MiB 5.94% ? MiBdownload https://tiup-mirrors.pingcap.com/prometheus-v5.0.3-linux-amd64.tar.gz 4.26 MiB / 39.84 MiB 10.68% ? Midownload https://tiup-mirrors.pingcap.com/prometheus-v5.0.3-linux-amd64.tar.gz 6.22 MiB / 39.84 MiB 15.61% ? Midownload https://tiup-mirrors.pingcap.com/prometheus-v5.0.3-linux-amd64.tar.gz 8.09 MiB / 39.84 MiB 20.31% 9.54download https://tiup-mirrors.pingcap.com/prometheus-v5.0.3-linux-amd64.tar.gz 10.00 MiB / 39.84 MiB 25.10% 9.5download https://tiup-mirrors.pingcap.com/prometheus-v5.0.3-linux-amd64.tar.gz 11.91 MiB / 39.84 MiB 29.88% 9.5download https://tiup-mirrors.pingcap.com/prometheus-v5.0.3-linux-amd64.tar.gz 13.80 MiB / 39.84 MiB 34.63% 9.5download https://tiup-mirrors.pingcap.com/prometheus-v5.0.3-linux-amd64.tar.gz 15.68 MiB / 39.84 MiB 39.35% 9.5download https://tiup-mirrors.pingcap.com/prometheus-v5.0.3-linux-amd64.tar.gz 17.61 MiB / 39.84 MiB 44.19% 9.5download https://tiup-mirrors.pingcap.com/prometheus-v5.0.3-linux-amd64.tar.gz 19.50 MiB / 39.84 MiB 48.94% 9.5download https://tiup-mirrors.pingcap.com/prometheus-v5.0.3-linux-amd64.tar.gz 21.41 MiB / 39.84 MiB 53.72% 9.5download https://tiup-mirrors.pingcap.com/prometheus-v5.0.3-linux-amd64.tar.gz 23.31 MiB / 39.84 MiB 58.51% 9.5download https://tiup-mirrors.pingcap.com/prometheus-v5.0.3-linux-amd64.tar.gz 25.13 MiB / 39.84 MiB 63.08% 9.5download https://tiup-mirrors.pingcap.com/prometheus-v5.0.3-linux-amd64.tar.gz 27.12 MiB / 39.84 MiB 68.08% 9.5download https://tiup-mirrors.pingcap.com/prometheus-v5.0.3-linux-amd64.tar.gz 29.03 MiB / 39.84 MiB 72.86% 9.5download https://tiup-mirrors.pingcap.com/prometheus-v5.0.3-linux-amd64.tar.gz 30.94 MiB / 39.84 MiB 77.65% 9.5download https://tiup-mirrors.pingcap.com/prometheus-v5.0.3-linux-amd64.tar.gz 32.78 MiB / 39.84 MiB 82.27% 9.5download https://tiup-mirrors.pingcap.com/prometheus-v5.0.3-linux-amd64.tar.gz 34.73 MiB / 39.84 MiB 87.18% 9.5download https://tiup-mirrors.pingcap.com/prometheus-v5.0.3-linux-amd64.tar.gz 36.61 MiB / 39.84 MiB 91.88% 9.5download https://tiup-mirrors.pingcap.com/prometheus-v5.0.3-linux-amd64.tar.gz 38.58 MiB / 39.84 MiB 96.82% 9.5download https://tiup-mirrors.pingcap.com/prometheus-v5.0.3-linux-amd64.tar.gz 39.84 MiB / 39.84 MiB 100.00% 10.13 MiB/s
download https://tiup-mirrors.pingcap.com/grafana-v5.0.3-linux-amd64.tar.gz 8.01 MiB / 54.25 MiB 14.77% 9.54 Midownload https://tiup-mirrors.pingcap.com/grafana-v5.0.3-linux-amd64.tar.gz 9.94 MiB / 54.25 MiB 18.33% 9.54 Midownload https://tiup-mirrors.pingcap.com/grafana-v5.0.3-linux-amd64.tar.gz 11.83 MiB / 54.25 MiB 21.80% 9.54 Mdownload https://tiup-mirrors.pingcap.com/grafana-v5.0.3-linux-amd64.tar.gz 13.76 MiB / 54.25 MiB 25.36% 9.54 Mdownload https://tiup-mirrors.pingcap.com/grafana-v5.0.3-linux-amd64.tar.gz 15.66 MiB / 54.25 MiB 28.87% 9.54 Mdownload https://tiup-mirrors.pingcap.com/grafana-v5.0.3-linux-amd64.tar.gz 17.55 MiB / 54.25 MiB 32.35% 9.54 Mdownload https://tiup-mirrors.pingcap.com/grafana-v5.0.3-linux-amd64.tar.gz 19.47 MiB / 54.25 MiB 35.88% 9.54 Mdownload https://tiup-mirrors.pingcap.com/grafana-v5.0.3-linux-amd64.tar.gz 21.33 MiB / 54.25 MiB 39.31% 9.54 Mdownload https://tiup-mirrors.pingcap.com/grafana-v5.0.3-linux-amd64.tar.gz 23.24 MiB / 54.25 MiB 42.84% 9.54 Mdownload https://tiup-mirrors.pingcap.com/grafana-v5.0.3-linux-amd64.tar.gz 25.15 MiB / 54.25 MiB 46.35% 9.53 Mdownload https://tiup-mirrors.pingcap.com/grafana-v5.0.3-linux-amd64.tar.gz 27.03 MiB / 54.25 MiB 49.82% 9.53 Mdownload https://tiup-mirrors.pingcap.com/grafana-v5.0.3-linux-amd64.tar.gz 28.94 MiB / 54.25 MiB 53.33% 9.53 Mdownload https://tiup-mirrors.pingcap.com/grafana-v5.0.3-linux-amd64.tar.gz 30.84 MiB / 54.25 MiB 56.85% 9.53 Mdownload https://tiup-mirrors.pingcap.com/grafana-v5.0.3-linux-amd64.tar.gz 32.76 MiB / 54.25 MiB 60.38% 9.53 Mdownload https://tiup-mirrors.pingcap.com/grafana-v5.0.3-linux-amd64.tar.gz 34.69 MiB / 54.25 MiB 63.95% 9.53 Mdownload https://tiup-mirrors.pingcap.com/grafana-v5.0.3-linux-amd64.tar.gz 36.58 MiB / 54.25 MiB 67.43% 9.53 Mdownload https://tiup-mirrors.pingcap.com/grafana-v5.0.3-linux-amd64.tar.gz 38.51 MiB / 54.25 MiB 70.99% 9.53 MiB/s^CGot signal interrupt (Component: playground ; PID: 8096)
Playground receive signal:  interrupt
prometheus quit
download https://tiup-mirrors.pingcap.com/grafana-v5.0.3-linux-amd64.tar.gz 40.33 MiB / 54.25 MiB 74.33% 9.53 Mdownload https://tiup-mirrors.pingcap.com/grafana-v5.0.3-linux-amd64.tar.gz 42.30 MiB / 54.25 MiB 77.96% 9.53 Mdownload https://tiup-mirrors.pingcap.com/grafana-v5.0.3-linux-amd64.tar.gz 44.22 MiB / 54.25 MiB 81.50% 9.53 Mdownload https://tiup-mirrors.pingcap.com/grafana-v5.0.3-linux-amd64.tar.gz 46.11 MiB / 54.25 MiB 84.98% 9.53 Mdownload https://tiup-mirrors.pingcap.com/grafana-v5.0.3-linux-amd64.tar.gz 48.05 MiB / 54.25 MiB 88.56% 9.53 MiB/s^C^C[tidb@node4210 conf]$ ^C
[tidb@node4210 conf]$ ^C
[tidb@node4210 conf]$ ^C
[tidb@node4210 conf]$ ^C

**[tidb@node4210 conf]$ tiup playground v5.0.3 --tiflash 0 --monitor=false --pd 1 --db 1 --kv 1** 
4
Starting component `playground`: /home/tidb/.tiup/components/playground/v1.5.4/tiup-playground v5.0.3 --tiflash 0 --monitor=false --pd 1 --db 1 --kv 1
Using the version v5.0.3 for version constraint "v5.0.3".

If you'd like to use a TiDB version other than v5.0.3, cancel and retry with the following arguments:
    Specify version manually:   tiup playground <version>
    Specify version range:      tiup playground ^5
    The nightly version:        tiup playground nightly

Playground Bootstrapping...
Start pd instance
The component `pd` version v5.0.3 is not installed; downloading from repository.
download https://tiup-mirrors.pingcap.com/pd-v5.0.3-linux-amd64.tar.gz 42.00 MiB / 42.00 MiB 100.00% 10.13 MiB/s
Start tikv instance
The component `tikv` version v5.0.3 is not installed; downloading from repository.
download https://tiup-mirrors.pingcap.com/tikv-v5.0.3-linux-amd64.tar.gz 7.79 MiB / 161.24 MiB 4.83% 11.99 MiB/download https://tiup-mirrors.pingcap.com/tikv-v5.0.3-linux-amd64.tar.gz 9.75 MiB / 161.24 MiB 6.05% 11.99 MiB/download https://tiup-mirrors.pingcap.com/tikv-v5.0.3-linux-amd64.tar.gz 11.66 MiB / 161.24 MiB 7.23% 11.99 MiBdownload https://tiup-mirrors.pingcap.com/tikv-v5.0.3-linux-amd64.tar.gz 13.56 MiB / 161.24 MiB 8.41% 11.84 MiBdownload https://tiup-mirrors.pingcap.com/tikv-v5.0.3-linux-amd64.tar.gz 15.47 MiB / 161.24 MiB 9.59% 11.84 MiBdownload https://tiup-mirrors.pingcap.com/tikv-v5.0.3-linux-amd64.tar.gz 17.37 MiB / 161.24 MiB 10.78% 11.84 Midownload https://tiup-mirrors.pingcap.com/tikv-v5.0.3-linux-amd64.tar.gz 19.28 MiB / 161.24 MiB 11.96% 11.69 Midownload https://tiup-mirrors.pingcap.com/tikv-v5.0.3-linux-amd64.tar.gz 21.16 MiB / 161.24 MiB 13.12% 11.69 Midownload https://tiup-mirrors.pingcap.com/tikv-v5.0.3-linux-amd64.tar.gz 23.06 MiB / 161.24 MiB 14.30% 11.69 Midownload https://tiup-mirrors.pingcap.com/tikv-v5.0.3-linux-amd64.tar.gz 24.97 MiB / 161.24 MiB 15.48% 11.55 Midownload https://tiup-mirrors.pingcap.com/tikv-v5.0.3-linux-amd64.tar.gz 26.86 MiB / 161.24 MiB 16.66% 11.55 Midownload https://tiup-mirrors.pingcap.com/tikv-v5.0.3-linux-amd64.tar.gz 28.80 MiB / 161.24 MiB 17.86% 11.55 Midownload https://tiup-mirrors.pingcap.com/tikv-v5.0.3-linux-amd64.tar.gz 30.47 MiB / 161.24 MiB 18.90% 11.39 Midownload https://tiup-mirrors.pingcap.com/tikv-v5.0.3-linux-amd64.tar.gz 30.47 MiB / 161.24 MiB 18.90% 11.39 Midownload https://tiup-mirrors.pingcap.com/tikv-v5.0.3-linux-amd64.tar.gz 30.47 MiB / 161.24 MiB 18.90% 11.39 Midownload https://tiup-mirrors.pingcap.com/tikv-v5.0.3-linux-amd64.tar.gz 30.47 MiB / 161.24 MiB 18.90% 10.66 Midownload https://tiup-mirrors.pingcap.com/tikv-v5.0.3-linux-amd64.tar.gz 30.47 MiB / 161.24 MiB 18.90% 10.66 Midownload https://tiup-mirrors.pingcap.com/tikv-v5.0.3-linux-amd64.tar.gz 31.36 MiB / 161.24 MiB 19.45% 10.66 Midownload https://tiup-mirrors.pingcap.com/tikv-v5.0.3-linux-amd64.tar.gz 35.16 MiB / 161.24 MiB 21.80% 10.47 Midownload https://tiup-mirrors.pingcap.com/tikv-v5.0.3-linux-amd64.tar.gz 38.85 MiB / 161.24 MiB 24.09% 10.47 Midownload https://tiup-mirrors.pingcap.com/tikv-v5.0.3-linux-amd64.tar.gz 40.76 MiB / 161.24 MiB 25.28% 10.47 Midownload https://tiup-mirrors.pingcap.com/tikv-v5.0.3-linux-amd64.tar.gz 42.69 MiB / 161.24 MiB 26.47% 10.61 Midownload https://tiup-mirrors.pingcap.com/tikv-v5.0.3-linux-amd64.tar.gz 44.59 MiB / 161.24 MiB 27.66% 10.61 Midownload https://tiup-mirrors.pingcap.com/tikv-v5.0.3-linux-amd64.tar.gz 46.50 MiB / 161.24 MiB 28.84% 10.61 Midownload https://tiup-mirrors.pingcap.com/tikv-v5.0.3-linux-amd64.tar.gz 48.37 MiB / 161.24 MiB 30.00% 10.54 Midownload https://tiup-mirrors.pingcap.com/tikv-v5.0.3-linux-amd64.tar.gz 50.31 MiB / 161.24 MiB 31.20% 10.54 Midownload https://tiup-mirrors.pingcap.com/tikv-v5.0.3-linux-amd64.tar.gz 52.22 MiB / 161.24 MiB 32.39% 10.54 Midownload https://tiup-mirrors.pingcap.com/tikv-v5.0.3-linux-amd64.tar.gz 54.12 MiB / 161.24 MiB 33.56% 10.47 Midownload https://tiup-mirrors.pingcap.com/tikv-v5.0.3-linux-amd64.tar.gz 56.00 MiB / 161.24 MiB 34.73% 10.47 Midownload https://tiup-mirrors.pingcap.com/tikv-v5.0.3-linux-amd64.tar.gz 57.94 MiB / 161.24 MiB 35.93% 10.47 Midownload https://tiup-mirrors.pingcap.com/tikv-v5.0.3-linux-amd64.tar.gz 59.83 MiB / 161.24 MiB 37.10% 10.41 Midownload https://tiup-mirrors.pingcap.com/tikv-v5.0.3-linux-amd64.tar.gz 61.72 MiB / 161.24 MiB 38.28% 10.41 Midownload https://tiup-mirrors.pingcap.com/tikv-v5.0.3-linux-amd64.tar.gz 63.66 MiB / 161.24 MiB 39.48% 10.41 Midownload https://tiup-mirrors.pingcap.com/tikv-v5.0.3-linux-amd64.tar.gz 65.56 MiB / 161.24 MiB 40.66% 10.36 Midownload https://tiup-mirrors.pingcap.com/tikv-v5.0.3-linux-amd64.tar.gz 67.47 MiB / 161.24 MiB 41.84% 10.36 Midownload https://tiup-mirrors.pingcap.com/tikv-v5.0.3-linux-amd64.tar.gz 69.37 MiB / 161.24 MiB 43.03% 10.36 Midownload https://tiup-mirrors.pingcap.com/tikv-v5.0.3-linux-amd64.tar.gz 71.28 MiB / 161.24 MiB 44.21% 10.30 Midownload https://tiup-mirrors.pingcap.com/tikv-v5.0.3-linux-amd64.tar.gz 73.18 MiB / 161.24 MiB 45.39% 10.30 Midownload https://tiup-mirrors.pingcap.com/tikv-v5.0.3-linux-amd64.tar.gz 75.08 MiB / 161.24 MiB 46.56% 10.30 Midownload https://tiup-mirrors.pingcap.com/tikv-v5.0.3-linux-amd64.tar.gz 76.92 MiB / 161.24 MiB 47.71% 10.25 Midownload https://tiup-mirrors.pingcap.com/tikv-v5.0.3-linux-amd64.tar.gz 78.89 MiB / 161.24 MiB 48.93% 10.25 Midownload https://tiup-mirrors.pingcap.com/tikv-v5.0.3-linux-amd64.tar.gz 80.81 MiB / 161.24 MiB 50.12% 10.25 Midownload https://tiup-mirrors.pingcap.com/tikv-v5.0.3-linux-amd64.tar.gz 82.72 MiB / 161.24 MiB 51.30% 10.21 Midownload https://tiup-mirrors.pingcap.com/tikv-v5.0.3-linux-amd64.tar.gz 84.62 MiB / 161.24 MiB 52.48% 10.21 Midownload https://tiup-mirrors.pingcap.com/tikv-v5.0.3-linux-amd64.tar.gz 86.50 MiB / 161.24 MiB 53.65% 10.21 Midownload https://tiup-mirrors.pingcap.com/tikv-v5.0.3-linux-amd64.tar.gz 88.41 MiB / 161.24 MiB 54.83% 10.16 Midownload https://tiup-mirrors.pingcap.com/tikv-v5.0.3-linux-amd64.tar.gz 90.36 MiB / 161.24 MiB 56.04% 10.16 Midownload https://tiup-mirrors.pingcap.com/tikv-v5.0.3-linux-amd64.tar.gz 92.23 MiB / 161.24 MiB 57.20% 10.16 Midownload https://tiup-mirrors.pingcap.com/tikv-v5.0.3-linux-amd64.tar.gz 94.14 MiB / 161.24 MiB 58.38% 10.12 Midownload https://tiup-mirrors.pingcap.com/tikv-v5.0.3-linux-amd64.tar.gz 96.03 MiB / 161.24 MiB 59.56% 10.12 Midownload https://tiup-mirrors.pingcap.com/tikv-v5.0.3-linux-amd64.tar.gz 97.89 MiB / 161.24 MiB 60.71% 10.12 Midownload https://tiup-mirrors.pingcap.com/tikv-v5.0.3-linux-amd64.tar.gz 99.84 MiB / 161.24 MiB 61.92% 10.08 Midownload https://tiup-mirrors.pingcap.com/tikv-v5.0.3-linux-amd64.tar.gz 101.73 MiB / 161.24 MiB 63.09% 10.08 Mdownload https://tiup-mirrors.pingcap.com/tikv-v5.0.3-linux-amd64.tar.gz 103.66 MiB / 161.24 MiB 64.29% 10.08 Mdownload https://tiup-mirrors.pingcap.com/tikv-v5.0.3-linux-amd64.tar.gz 105.56 MiB / 161.24 MiB 65.47% 10.05 Mdownload https://tiup-mirrors.pingcap.com/tikv-v5.0.3-linux-amd64.tar.gz 107.47 MiB / 161.24 MiB 66.65% 10.05 Mdownload https://tiup-mirrors.pingcap.com/tikv-v5.0.3-linux-amd64.tar.gz 109.14 MiB / 161.24 MiB 67.69% 10.05 Mdownload https://tiup-mirrors.pingcap.com/tikv-v5.0.3-linux-amd64.tar.gz 110.69 MiB / 161.24 MiB 68.65% 9.95 Midownload https://tiup-mirrors.pingcap.com/tikv-v5.0.3-linux-amd64.tar.gz 112.58 MiB / 161.24 MiB 69.82% 9.95 Midownload https://tiup-mirrors.pingcap.com/tikv-v5.0.3-linux-amd64.tar.gz 114.31 MiB / 161.24 MiB 70.90% 9.95 Midownload https://tiup-mirrors.pingcap.com/tikv-v5.0.3-linux-amd64.tar.gz 116.06 MiB / 161.24 MiB 71.98% 9.88 Midownload https://tiup-mirrors.pingcap.com/tikv-v5.0.3-linux-amd64.tar.gz 117.98 MiB / 161.24 MiB 73.17% 9.88 Midownload https://tiup-mirrors.pingcap.com/tikv-v5.0.3-linux-amd64.tar.gz 119.88 MiB / 161.24 MiB 74.35% 9.88 Midownload https://tiup-mirrors.pingcap.com/tikv-v5.0.3-linux-amd64.tar.gz 121.80 MiB / 161.24 MiB 75.54% 9.86 Midownload https://tiup-mirrors.pingcap.com/tikv-v5.0.3-linux-amd64.tar.gz 123.69 MiB / 161.24 MiB 76.71% 9.86 Midownload https://tiup-mirrors.pingcap.com/tikv-v5.0.3-linux-amd64.tar.gz 125.61 MiB / 161.24 MiB 77.90% 9.86 Midownload https://tiup-mirrors.pingcap.com/tikv-v5.0.3-linux-amd64.tar.gz 127.51 MiB / 161.24 MiB 79.08% 9.84 Midownload https://tiup-mirrors.pingcap.com/tikv-v5.0.3-linux-amd64.tar.gz 129.39 MiB / 161.24 MiB 80.25% 9.84 Midownload https://tiup-mirrors.pingcap.com/tikv-v5.0.3-linux-amd64.tar.gz 131.27 MiB / 161.24 MiB 81.41% 9.84 Midownload https://tiup-mirrors.pingcap.com/tikv-v5.0.3-linux-amd64.tar.gz 133.13 MiB / 161.24 MiB 82.57% 9.81 Midownload https://tiup-mirrors.pingcap.com/tikv-v5.0.3-linux-amd64.tar.gz 135.06 MiB / 161.24 MiB 83.76% 9.81 Midownload https://tiup-mirrors.pingcap.com/tikv-v5.0.3-linux-amd64.tar.gz 136.99 MiB / 161.24 MiB 84.96% 9.81 Midownload https://tiup-mirrors.pingcap.com/tikv-v5.0.3-linux-amd64.tar.gz 138.91 MiB / 161.24 MiB 86.15% 9.80 Midownload https://tiup-mirrors.pingcap.com/tikv-v5.0.3-linux-amd64.tar.gz 140.17 MiB / 161.24 MiB 86.93% 9.80 Midownload https://tiup-mirrors.pingcap.com/tikv-v5.0.3-linux-amd64.tar.gz 140.87 MiB / 161.24 MiB 87.36% 9.80 Midownload https://tiup-mirrors.pingcap.com/tikv-v5.0.3-linux-amd64.tar.gz 144.61 MiB / 161.24 MiB 89.69% 9.78 Midownload https://tiup-mirrors.pingcap.com/tikv-v5.0.3-linux-amd64.tar.gz 146.53 MiB / 161.24 MiB 90.88% 9.78 Midownload https://tiup-mirrors.pingcap.com/tikv-v5.0.3-linux-amd64.tar.gz 148.42 MiB / 161.24 MiB 92.05% 9.78 Midownload https://tiup-mirrors.pingcap.com/tikv-v5.0.3-linux-amd64.tar.gz 150.33 MiB / 161.24 MiB 93.23% 9.76 Midownload https://tiup-mirrors.pingcap.com/tikv-v5.0.3-linux-amd64.tar.gz 152.25 MiB / 161.24 MiB 94.42% 9.76 Midownload https://tiup-mirrors.pingcap.com/tikv-v5.0.3-linux-amd64.tar.gz 154.08 MiB / 161.24 MiB 95.56% 9.76 Midownload https://tiup-mirrors.pingcap.com/tikv-v5.0.3-linux-amd64.tar.gz 156.03 MiB / 161.24 MiB 96.77% 9.75 Midownload https://tiup-mirrors.pingcap.com/tikv-v5.0.3-linux-amd64.tar.gz 157.97 MiB / 161.24 MiB 97.97% 9.75 Midownload https://tiup-mirrors.pingcap.com/tikv-v5.0.3-linux-amd64.tar.gz 159.86 MiB / 161.24 MiB 99.14% 9.75 Midownload https://tiup-mirrors.pingcap.com/tikv-v5.0.3-linux-amd64.tar.gz 161.24 MiB / 161.24 MiB 100.00% 9.30 MiB/s
Start tidb instance
The component `tidb` version v5.0.3 is not installed; downloading from repository.
download https://tiup-mirrors.pingcap.com/tidb-v5.0.3-linux-amd64.tar.gz 11.67 MiB / 45.91 MiB 25.42% 9.50 MiB/download https://tiup-mirrors.pingcap.com/tidb-v5.0.3-linux-amd64.tar.gz 13.58 MiB / 45.91 MiB 29.57% 9.50 MiB/download https://tiup-mirrors.pingcap.com/tidb-v5.0.3-linux-amd64.tar.gz 15.48 MiB / 45.91 MiB 33.72% 9.50 MiB/download https://tiup-mirrors.pingcap.com/tidb-v5.0.3-linux-amd64.tar.gz 17.38 MiB / 45.91 MiB 37.86% 9.50 MiB/download https://tiup-mirrors.pingcap.com/tidb-v5.0.3-linux-amd64.tar.gz 19.27 MiB / 45.91 MiB 41.98% 9.50 MiB/download https://tiup-mirrors.pingcap.com/tidb-v5.0.3-linux-amd64.tar.gz 21.18 MiB / 45.91 MiB 46.13% 9.50 MiB/download https://tiup-mirrors.pingcap.com/tidb-v5.0.3-linux-amd64.tar.gz 23.07 MiB / 45.91 MiB 50.25% 9.50 MiB/download https://tiup-mirrors.pingcap.com/tidb-v5.0.3-linux-amd64.tar.gz 24.92 MiB / 45.91 MiB 54.28% 9.49 MiB/download https://tiup-mirrors.pingcap.com/tidb-v5.0.3-linux-amd64.tar.gz 26.67 MiB / 45.91 MiB 58.09% 9.49 MiB/download https://tiup-mirrors.pingcap.com/tidb-v5.0.3-linux-amd64.tar.gz 28.69 MiB / 45.91 MiB 62.48% 9.49 MiB/download https://tiup-mirrors.pingcap.com/tidb-v5.0.3-linux-amd64.tar.gz 30.47 MiB / 45.91 MiB 66.36% 9.48 MiB/download https://tiup-mirrors.pingcap.com/tidb-v5.0.3-linux-amd64.tar.gz 32.50 MiB / 45.91 MiB 70.78% 9.48 MiB/download https://tiup-mirrors.pingcap.com/tidb-v5.0.3-linux-amd64.tar.gz 34.42 MiB / 45.91 MiB 74.97% 9.48 MiB/download https://tiup-mirrors.pingcap.com/tidb-v5.0.3-linux-amd64.tar.gz 36.28 MiB / 45.91 MiB 79.02% 9.49 MiB/download https://tiup-mirrors.pingcap.com/tidb-v5.0.3-linux-amd64.tar.gz 38.22 MiB / 45.91 MiB 83.24% 9.49 MiB/download https://tiup-mirrors.pingcap.com/tidb-v5.0.3-linux-amd64.tar.gz 40.02 MiB / 45.91 MiB 87.17% 9.49 MiB/download https://tiup-mirrors.pingcap.com/tidb-v5.0.3-linux-amd64.tar.gz 41.95 MiB / 45.91 MiB 91.37% 9.49 MiB/download https://tiup-mirrors.pingcap.com/tidb-v5.0.3-linux-amd64.tar.gz 43.90 MiB / 45.91 MiB 95.61% 9.49 MiB/download https://tiup-mirrors.pingcap.com/tidb-v5.0.3-linux-amd64.tar.gz 45.80 MiB / 45.91 MiB 99.76% 9.49 MiB/download https://tiup-mirrors.pingcap.com/tidb-v5.0.3-linux-amd64.tar.gz 45.91 MiB / 45.91 MiB 100.00% 9.97 MiB/s
Waiting for tidb instances ready
127.0.0.1:4000 ... Done

Do you see if there are too many printed things, so please optimize the downloaded UI ！！！！！！

**Comment by AstroProfundis** [comment] 2021-08-18 08:12
I believe restarting the terminal would fix the progress issue.

**Comment by glkappe** [comment] 2021-08-19 06:31
what's mean

**Comment by qqqdan** [comment] 2021-08-25 08:23
For the “ --monitor=false” issue，it is caused by an issue for the third party tool we use.

**Comment by qqqdan** [comment] 2021-08-25 09:25
We will add a new option --without-monitor to disable monitors in v1.6.0 . 
https://github.com/pingcap/tiup/pull/1512

**Comment by qqqdan** [comment] 2022-01-18 06:22
--without-monitor  added , close this issue

**Closed** 2022-01-18 06:22 UTC
Labels: type/bug
