### ISSUE TITLE
Display some message for impossible auto-fixing

### ISSUE THREAD

**Issue by hhkbp2** [pingcap/tiup#335] opened 2020-05-25 07:12 UTC
Hi there,

When we use `tiup check --apply`, it's a bit confusing if the output doesn't show any message for those checks impossible to fix. Usually a program succeeds silently but it outputs some message when it fails or doesn't support. I suggest to add some message for these checks that could not be fixed, in:

https://github.com/pingcap-incubator/tiup-cluster/blob/master/cmd/cluster/command/check.go#L399

**Comment by lucklove** [comment] 2020-06-28 16:55
Could you provide your tiup version?
```
tiup --version
```

Is this issue still exists in the newest version?

**Comment by hhkbp2** [comment] 2020-06-29 03:26
PR #550 is created to fix this issue. PTAL.

**Comment by AstroProfundis** [comment] 2020-06-29 03:51
At present, if a failed check is impossible to be fixed by us, it will show a message/suggestion in the check result table.

The problem is, there will **always** be something we can not fix (i.e., cpu threads, memory size, os version, etc.) and I think it's not a good experience to show error message for user for them.

**Comment by hhkbp2** [comment] 2020-06-29 04:30
> At present, if a failed check is impossible to be fixed by us, it will show a message/suggestion in the check result table.
> 
> The problem is, there will **always** be something we can not fix (i.e., cpu threads, memory size, os version, etc.) and I think it's not a good experience to show error message for user for them.

So if there is something that can not be fixed, it just does nothing and keep silent about this fact that "this check failure can not be fixed" and let the user to guess what happens after running "check --apply"? Are you sure it's a good experience?

**Comment by AstroProfundis** [comment] 2020-06-29 05:55
Ah, my fault, this was about the message in check result table, not the command itself, then it looks fine for me.

**Closed** 2020-06-29 08:40 UTC
Labels: status/discuss
