### ISSUE TITLE
tiup cluster deploy will fail

### ISSUE THREAD

**Issue by ZhenhanGong** [pingcap/tiup#991] opened 2020-12-15 08:19 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
$ tiup cluster deploy test-compression nightly ./topology.yml --user root -p

2. What did you expect to see?
Succeed to deploy a cluster.

3. What did you see instead?
+ Copy files
  - Copy pd -> 172.16.5.187 ... Done
  - Copy tikv -> 172.16.5.187 ... Done
  - Copy tikv -> 172.16.5.187 ... Done
  - Copy tikv -> 172.16.5.187 ... Done
  - Copy tidb -> 172.16.5.187 ... Done
  - Copy tiflash -> 172.16.5.187 ... Done
  - Copy prometheus -> 172.16.5.187 ... **Error**
  - Copy grafana -> 172.16.5.187 ... **Error**
  - Copy node_exporter -> 172.16.5.187 ... Done
  - Copy blackbox_exporter -> 172.16.5.187 ... Done

**Error**: init config failed: 172.16.5.187:9090: executor.ssh.execute_failed: Failed to execute command over SSH for 'root@172.16.5.187:22' {ssh_stderr: zsh:1: no matches found: /tidb-deploy/prometheus-9090/conf/*.rules.yml
, ssh_stdout: , ssh_command: export LANG=C; PATH=$PATH:/usr/bin:/usr/sbin rm -f /tidb-deploy/prometheus-9090/conf/*.rules.yml}, cause: Process exited with status 1

4. What version of TiUP are you using (`tiup --version`)?
v1.2.5 tiup
Go Version: go1.13
Git Branch: release-1.2
GitHash: 5b9cf5d

5. A feasible workaround:
Seems Tiup will remove files before deploy a new cluster, but executing "rm -f /tidb-deploy/prometheus-9090/conf/*.rules.yml" will fail since there is no such file, and thus cause process exit.
workaround:
$ touch 1.rules.yml
touch a trivial file at promethesus folder before execute tiup deploy command.
$ touch 1.json
touch a file at grafana folder as well

**Comment by AstroProfundis** [comment] 2020-12-16 08:09
It seems you are using zsh as default shell on the remote, this should be a duplicate of #974 

Could you confirm if #982 fixes it?

**Comment by ZhenhanGong** [comment] 2020-12-16 09:19
Yes, it's a duplicate of #974 
But I think #982 did not fix the issue.

I git clone the newest commit & make the project then run cluster deploy command but seems the problem still exists.
I have to touch an xxx.rules.yml file at tidb-deploy/prometheus-9091/conf folder, and touch another xxx.json file at tidb-deploy/grafana-3001/dashboards folder to get the tiup deploy command work.

**Comment by ZhenhanGong** [comment] 2020-12-16 09:36
Yes, it's a duplicate of #974
And I think #982 did fix the issue.

## What I did:
1. $ git clone https://github.com/pingcap/tiup
2. $ make -j40
3. $ ./bin/tiup-cluster deploy ...
And succeed to deploy a cluster.

**Closed** 2020-12-16 09:36 UTC
Labels: category/monitoring, category/stability, type/bug, type/duplicate
