### ISSUE TITLE
Grafana 监控部分指标错误

### ISSUE THREAD

**Issue by swrd** [pingcap/tiup#940] opened 2020-11-26 03:26 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

- 部分grafana 监控指标提示NO data
![image](https://user-images.githubusercontent.com/5057571/100304432-b5d55d80-2fd9-11eb-844e-4ea85e03df03.png)
![image](https://user-images.githubusercontent.com/5057571/100304529-ecab7380-2fd9-11eb-93ca-60a6c6815c4e.png)

- etcd disk fsync 指标监控到了tidb 节点的磁盘，从而报出 pd etcd磁盘挂掉的错误
![image](https://user-images.githubusercontent.com/5057571/100304462-c71e6a00-2fd9-11eb-96ec-b327a82763e3.png)
![image](https://user-images.githubusercontent.com/5057571/100304625-182e5e00-2fda-11eb-88a5-0f0233003073.png)

2. What did you expect to see?

3. What did you see instead?

4. What version of TiUP are you using (`tiup --version`)?

tiup --version
v1.2.1 tiup
Go Version: go1.13
Git Branch: release-1.2
GitHash: b4059fe

**Comment by 9547** [comment] 2020-11-26 16:01
IMO, the Grafana alerts dashboard only displays the critical and error alerts, while the etcd disk fsync is not critical or error?

**Comment by lucklove** [comment] 2020-12-01 03:42
Based on the information you provided, we can't confirm where the problem is since we can't reproduce this. Please submit an issue on https://asktug.com/ if you get into problem in production environment. Closing this issue, if you have more information, please reopen it.

**Closed by lucklove** 2020-12-01 03:42 UTC
Labels: type/bug
