### ISSUE TITLE
Reduce memory usage when downloading components

### ISSUE THREAD

**Issue by lonng** [pingcap/tiup#443] opened 2020-06-06 12:32 UTC
## Feature Request

Currently, we use memory buffer to cache downloaded tarball, which will consume a large of memory if the tarball is huge (e.g: tiflash ~600M). The situation will get worse if we download concurrently (e.g tiup-cluster will download multiple components parallelly, 2G+ memory usage when use tiup-cluster to deploy a production cluster)。

We must reduce memory usage when downloading components.

**Comment by AstroProfundis** [comment] 2020-07-27 12:55
related, and maybe a dupe of #299

**Comment by lonng** [comment] 2020-07-28 02:26
@AstroProfundis I think it's better to close the #299

**Closed** 2020-09-22 09:24 UTC
Labels: status/help-wanted, type/enhancement
