### ISSUE TITLE
playground can't start 2 tidb instances

### ISSUE THREAD

**Issue by cyliu0** [pingcap/tiup#1607] opened 2021-11-02 03:26 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

```
# tiup playground nightly --tiflash 0 --db 2
```

2. What did you expect to see?
Start 2 tidb instances

3. What did you see instead?
playground started the second tidb but failed to start the first one.
```
127.0.0.1:4000 ... ⠴
127.0.0.1:4001 ... Done
[mysql] 2021/11/02 11:18:15 packets.go:37: read tcp 127.0.0.1:39286->127.0.0.1:4000: read: connection reset by peer
tidb quit: exit status 1
[2021/11/02 11:18:15.464 +08:00] [INFO] [domain.go:1135] ["TelemetryReportLoop exited."]
[2021/11/02 11:18:15.469 +08:00] [INFO] [manager.go:302] ["revoke session"] ["owner info"="[bindinfo] /tidb/bindinfo/owner ownerManager a6c01571-3e6b-4a14-bd33-3ae4087e40cf"] [error="rpc error: code = Canceled desc = grpc: the client connection is closing"]
[2021/11/02 11:18:15.469 +08:00] [INFO] [domain.go:1102] ["handleEvolvePlanTasksLoop exited."]
[2021/11/02 11:18:15.513 +08:00] [INFO] [manager.go:302] ["revoke session"] ["owner info"="[stats] /tidb/stats/owner ownerManager a6c01571-3e6b-4a14-bd33-3ae4087e40cf"] [error="rpc error: code = Canceled desc = grpc: the client connection is closing"]
[2021/11/02 11:18:15.513 +08:00] [INFO] [domain.go:1369] ["updateStatsWorker exited."]
[2021/11/02 11:18:15.513 +08:00] [INFO] [domain.go:685] ["domain closed"] ["take time"=2.585117801s]
[2021/11/02 11:18:15.514 +08:00] [INFO] [gc_worker.go:227] ["[gc worker] quit"] [uuid=5f37a9deda8001a]
[2021/11/02 11:18:15.514 +08:00] [ERROR] [client.go:750] ["[pd] fetch pending tso requests error"] [dc-location=global] [error="[PD:client:ErrClientGetTSO]context canceled: context canceled"]
[2021/11/02 11:18:15.514 +08:00] [INFO] [client.go:669] ["[pd] exit tso dispatcher"] [dc-location=global]
[2021/11/02 11:18:15.514 +08:00] [FATAL] [main.go:670] ["failed to create the server"] [error="unix socket /tmp/tidb.sock exists and is functional, not removing it"] [stack="main.createServer\n\t/home/jenkins/agent/workspace/build_tidb_multi_branch_master/go/src/github.co
m/pingcap/tidb/tidb-server/main.go:670\nmain.main\n\t/home/jenkins/agent/workspace/build_tidb_multi_branch_master/go/src/github.com/pingcap/tidb/tidb-server/main.go:199\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:225"] [stack="main.createServer\n\t/home/jenkins/age
nt/workspace/build_tidb_multi_branch_master/go/src/github.com/pingcap/tidb/tidb-server/main.go:670\nmain.main\n\t/home/jenkins/agent/workspace/build_tidb_multi_branch_master/go/src/github.com/pingcap/tidb/tidb-server/main.go:199\nruntime.main\n\t/usr/local/go/src/runtime/
Waiting for tidb instances ready
127.0.0.1:4000 ... Error
127.0.0.1:4001 ... Done
CLUSTER START SUCCESSFULLY, Enjoy it ^-^
To connect TiDB: mysql --comments --host 127.0.0.1 --port 4001 -u root -p (no password)
To view the dashboard: http://127.0.0.1:2379/dashboard
PD client endpoints: [127.0.0.1:2379]
To view the Prometheus: http://127.0.0.1:9090
To view the Grafana: http://127.0.0.1:3000
```

4. What version of TiUP are you using (`tiup --version`)?
```
# tiup --version
1.6.1 tiup
Go Version: go1.17.2
Git Ref: v1.6.1
GitHash: 1f6ca2b18e5c96c075efb4c08084d6dc8659050b
```

**Comment by AstroProfundis** [comment] 2021-11-04 03:25
I think this is a dupe of #1593 which I believe only breaks several nightly versions.

**Closed by AstroProfundis** 2021-11-04 03:25 UTC
Labels: type/bug
